### ISSUE TITLE
scp AssertionError (self._depth > 0) while downloading a remote directory

### ISSUE THREAD

**Issue by alanbchristie** [VisTrails/tej#30]
I've encountered this fault recursing through remote directories and wondered whether anyone else has seen this with tej?

-   tej 0.6
-   scp 0.13.1

The files are pulled back (from the remote `results` directory) before the assert fires and I have fixed the error that occurs with `| true`, e.g.: -

```
tej download $DESTINATION --id $JOB results | true
```

As it's an assert in `scp` the fault may well be in that module so an issue has been raised in the scp project (https://github.com/jbardin/scp.py/issues/129).

The stack-trace of the assert is: -

```
Traceback (most recent call last):
  File "/usr/bin/tej", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tej/main.py", line 226, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/tej/main.py", line 48, in wrapped
    return f(args)
  File "/usr/lib/python2.7/site-packages/tej/main.py", line 85, in _download
    directory='.')
  File "/usr/lib/python2.7/site-packages/tej/submission.py", line 578, in download
    recursive=recursive)
  File "/usr/lib/python2.7/site-packages/scp.py", line 238, in get
    self._recv_all()
  File "/usr/lib/python2.7/site-packages/scp.py", line 389, in _recv_all
    command[code](msg[1:])
  File "/usr/lib/python2.7/site-packages/scp.py", line 504, in _recv_popd
    assert self._depth > 0
AssertionError
```

**Comment by remram44** [comment]
Yes this is a legitimate bug in scp.py 0.13.1. tej is not doing anything abnormal. scp.py 0.13.2 will fix.

I should probably run tej's testsuite when I make changes to scp.py.
